---
repos:
  - repo: https://github.com/polymathrobotics/polymath_code_standard
    rev: v2.2.0
    hooks:
      # Basic checks and fixes that apply to any text file and the git repository itself
      - id: polymath-general
      - id: polymath-copyright
        args: [--license, Apache-2.0, --copyright-org, 'Polymath Robotics, Inc.', --reuse-style]
      # Specific languages
      - id: polymath-python
      - id: polymath-cpp
      - id: polymath-shell
      - id: polymath-cmake
      - id: polymath-markdown
      - id: polymath-yaml
      - id: polymath-json
